#!/usr/bin/env python3
"""
Build address autocomplete index from OpenAddresses data.

Parses CA address GeoJSON files, normalizes addresses, and loads into
a SQLite database with FTS5 full-text search for prefix queries.

The output database is used by the Cloudflare Worker via D1 for
sub-50ms address autocomplete.

Input: data/raw/openaddresses/*-addresses-*.geojson (line-delimited GeoJSON)
Output: data/processed/addresses.db (SQLite with FTS5)
"""

import json
import sqlite3
import time

import numpy as np
from pathlib import Path

INPUT_DIR = Path("data/raw/openaddresses")
OUTPUT_DB = Path("data/processed/addresses.db")


def normalize_street(street):
    """Normalize street name: title case, expand common abbreviations."""
    if not street:
        return ""
    s = street.strip().title()
    # Common suffix expansions
    replacements = {
        " St": " Street", " Ave": " Avenue", " Blvd": " Boulevard",
        " Dr": " Drive", " Ln": " Lane", " Rd": " Road", " Ct": " Court",
        " Pl": " Place", " Cir": " Circle", " Ter": " Terrace",
        " Trl": " Trail", " Pkwy": " Parkway", " Hwy": " Highway",
    }
    for old, new in replacements.items():
        if s.endswith(old):
            s = s[:-len(old)] + new
            break
    return s


# Census-verified street name corrections for doubled-word data quality issues.
# Generated by geocoding the deduplicated form and confirming it resolves.
# 1,139 corrections out of 1,856 doubled street names (717 are real names).
_STREET_CORRECTIONS: dict[str, str] | None = None

def load_street_corrections():
    global _STREET_CORRECTIONS
    corrections_path = Path("data/processed/street_corrections.json")
    if corrections_path.exists():
        import json as _json
        with open(corrections_path) as f:
            _STREET_CORRECTIONS = _json.load(f)
    else:
        _STREET_CORRECTIONS = {}


def correct_street(raw_street: str) -> str:
    """Apply Census-verified corrections to doubled street names."""
    if _STREET_CORRECTIONS is None:
        load_street_corrections()
    return _STREET_CORRECTIONS.get(raw_street, raw_street)


def parse_address(props, coords):
    """Parse a single address feature into a normalized record."""
    number = (props.get("number") or "").strip()
    raw_street = (props.get("street") or "").strip()
    street = normalize_street(correct_street(raw_street))
    unit = (props.get("unit") or "").strip()
    city = (props.get("city") or "").strip().title()
    postcode = (props.get("postcode") or "").strip()

    if not number or not street or not city:
        return None

    # Build full address string for search
    parts = [number, street]
    if unit:
        parts.append(f"#{unit}")
    full = " ".join(parts)

    # Display string includes city and zip
    display_parts = [full]
    if city:
        display_parts.append(city)
    display_parts.append("CA")
    if postcode:
        display_parts.append(postcode)
    display = ", ".join(display_parts)

    lon, lat = coords[0], coords[1]
    if not (-124.5 <= lon <= -114.0 and 32.5 <= lat <= 42.0):
        return None

    return {
        "address": full,
        "city": city,
        "postcode": postcode,
        "display": display,
        "lat": round(lat, 6),
        "lon": round(lon, 6),
    }


def main():
    OUTPUT_DB.parent.mkdir(parents=True, exist_ok=True)
    if OUTPUT_DB.exists():
        OUTPUT_DB.unlink()

    conn = sqlite3.connect(str(OUTPUT_DB))
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA synchronous=OFF")

    # Main address table
    conn.execute("""
        CREATE TABLE addresses (
            id INTEGER PRIMARY KEY,
            address TEXT NOT NULL,
            city TEXT,
            postcode TEXT,
            display TEXT NOT NULL,
            lat REAL NOT NULL,
            lon REAL NOT NULL
        )
    """)

    # B-tree index for prefix search (LIKE 'query%' with COLLATE NOCASE)
    # Much smaller and faster than FTS5 for simple prefix matching.
    conn.execute("CREATE INDEX idx_address ON addresses(address COLLATE NOCASE)")

    geojson_files = sorted(INPUT_DIR.glob("*-addresses-*.geojson"))
    print(f"Processing {len(geojson_files)} address files...")

    total = 0
    skipped = 0
    seen = set()  # deduplicate by (number, street, city)
    t0 = time.time()
    batch = []
    batch_size = 50000

    for fpath in geojson_files:
        county = fpath.name.split("-addresses-")[0]
        file_count = 0

        with open(fpath) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    feat = json.loads(line)
                except json.JSONDecodeError:
                    continue

                props = feat.get("properties") or {}
                geom = feat.get("geometry") or {}
                coords = geom.get("coordinates") if geom else None
                if not coords or len(coords) < 2:
                    skipped += 1
                    continue

                record = parse_address(props, coords)
                if not record:
                    skipped += 1
                    continue

                # Deduplicate
                dedup_key = (record["address"].lower(), record["city"].lower())
                if dedup_key in seen:
                    skipped += 1
                    continue
                seen.add(dedup_key)

                batch.append(record)
                file_count += 1

                if len(batch) >= batch_size:
                    _flush_batch(conn, batch)
                    batch = []

        total += file_count
        if total % 500000 < file_count:
            elapsed = time.time() - t0
            print(f"  {total:,} addresses ({elapsed:.0f}s, {county})")

    # Final flush
    if batch:
        _flush_batch(conn, batch)

    elapsed = time.time() - t0
    print(f"\n  {total:,} addresses loaded, {skipped:,} skipped ({elapsed:.0f}s)")

    conn.commit()

    # Backfill missing postcodes from nearest zip centroid
    missing = conn.execute(
        "SELECT COUNT(*) FROM addresses WHERE postcode = '' OR postcode IS NULL"
    ).fetchone()[0]
    if missing > 0:
        print(f"  Backfilling {missing:,} missing postcodes...")
        import pgeocode
        from scipy.spatial import cKDTree

        nomi = pgeocode.Nominatim("us")
        ca_zips = nomi._data[nomi._data["state_code"] == "CA"][
            ["postal_code", "latitude", "longitude"]
        ].dropna()
        zip_tree = cKDTree(ca_zips[["latitude", "longitude"]].values)
        zip_codes = ca_zips["postal_code"].values

        rows = conn.execute(
            "SELECT id, lat, lon FROM addresses WHERE postcode = '' OR postcode IS NULL"
        ).fetchall()
        lats = np.array([r[1] for r in rows])
        lons = np.array([r[2] for r in rows])
        _, idx = zip_tree.query(np.column_stack([lats, lons]))

        updates = [(zip_codes[idx[i]], rows[i][0]) for i in range(len(rows))]
        conn.executemany("UPDATE addresses SET postcode=? WHERE id=?", updates)

        # Fix display strings to include the new postcode
        conn.execute("""
            UPDATE addresses SET display = address || ', ' || city || ', CA, ' || postcode
            WHERE display NOT LIKE '%, CA, _____'
            AND postcode != '' AND city != ''
        """)
        conn.commit()
        print(f"  Done.")

    # Stats
    row = conn.execute("SELECT COUNT(*) FROM addresses").fetchone()
    print(f"  Final count: {row[0]:,}")
    db_size = OUTPUT_DB.stat().st_size
    print(f"  Database size: {db_size / 1e6:.0f} MB")

    conn.close()
    print("Done.")


def _flush_batch(conn, batch):
    conn.executemany(
        "INSERT INTO addresses (address, city, postcode, display, lat, lon) VALUES (?, ?, ?, ?, ?, ?)",
        [(r["address"], r["city"], r["postcode"], r["display"], r["lat"], r["lon"]) for r in batch],
    )


if __name__ == "__main__":
    main()
